INSERT INTO TRADES (TRADE_ID, VERSION, COUNTER_PARTY_ID, BOOK_ID, MATURITY_DATE, CREATED_DATE, IS_EXPIRED)
    VALUES('T1', '1', 'CP-1', 'B1', to_timestamp('20/05/2021', 'DD/MM/YYYY'), current_timestamp, 'N');

INSERT INTO TRADES (TRADE_ID, VERSION, COUNTER_PARTY_ID, BOOK_ID, MATURITY_DATE, CREATED_DATE, IS_EXPIRED)
    VALUES('T2', '2', 'CP-2', 'B1', to_timestamp('20/05/2021', 'DD/MM/YYYY'), current_timestamp, 'N');

INSERT INTO TRADES (TRADE_ID, VERSION, COUNTER_PARTY_ID, BOOK_ID, MATURITY_DATE, CREATED_DATE, IS_EXPIRED)
    VALUES('T2', '1', 'CP-1', 'B1', to_timestamp('20/12/2020', 'DD/MM/YYYY'), to_timestamp('20/05/2020', 'DD/MM/YYYY'), 'N');

INSERT INTO TRADES (TRADE_ID, VERSION, COUNTER_PARTY_ID, BOOK_ID, MATURITY_DATE, CREATED_DATE, IS_EXPIRED)
    VALUES('T3', '3', 'CP-3', 'B2', to_timestamp('20/12/2014', 'DD/MM/YYYY'), current_timestamp, 'Y');
